/home/jack/Documents/home_lab/automateVMs/.venv/lib/python3.12/site-packages/ansible/_internal/ansible_collections:
  ansible._protomatter:
    version: 2.19.3
/home/jack/Documents/home_lab/automateVMs/.venv/lib/python3.12/site-packages/ansible_collections:
  amazon.aws:
    version: 10.1.2
  ansible.netcommon:
    version: 8.1.0
  ansible.posix:
    version: 2.1.0
  ansible.utils:
    version: 6.0.0
  ansible.windows:
    version: 3.2.0
  arista.eos:
    version: 12.0.0
  awx.awx:
    version: 24.6.1
  azure.azcollection:
    version: 3.9.0
  check_point.mgmt:
    version: 6.5.0
  chocolatey.chocolatey:
    version: 1.5.3
  cisco.aci:
    version: 2.12.0
  cisco.dnac:
    version: 6.40.0
  cisco.intersight:
    version: 2.6.0
  cisco.ios:
    version: 11.1.0
  cisco.iosxr:
    version: 12.0.0
  cisco.meraki:
    version: 2.21.8
  cisco.mso:
    version: 2.11.0
  cisco.nxos:
    version: 11.0.0
  cisco.ucs:
    version: 1.16.0
  cloudscale_ch.cloud:
    version: 2.5.2
  community.aws:
    version: 10.0.0
  community.ciscosmb:
    version: 1.0.11
  community.crypto:
    version: 3.0.4
  community.digitalocean:
    version: 1.27.0
  community.dns:
    version: 3.3.4
  community.docker:
    version: 4.8.1
  community.general:
    version: 11.4.0
  community.grafana:
    version: 2.3.0
  community.hashi_vault:
    version: 7.0.0
  community.hrobot:
    version: 2.5.2
  community.library_inventory_filtering_v1:
    version: 1.1.4
  community.libvirt:
    version: 2.0.0
  community.mongodb:
    version: 1.7.10
  community.mysql:
    version: 3.16.0
  community.okd:
    version: 5.0.0
  community.postgresql:
    version: 4.1.0
  community.proxmox:
    version: 1.3.0
  community.proxysql:
    version: 1.6.0
  community.rabbitmq:
    version: 1.6.0
  community.routeros:
    version: 3.12.1
  community.sap_libs:
    version: 1.5.0
  community.sops:
    version: 2.2.4
  community.vmware:
    version: 5.9.0
  community.windows:
    version: 3.0.1
  community.zabbix:
    version: 4.1.1
  containers.podman:
    version: 1.18.0
  cyberark.conjur:
    version: 1.3.7
  cyberark.pas:
    version: 1.0.35
  dellemc.enterprise_sonic:
    version: 3.0.0
  dellemc.openmanage:
    version: 9.12.3
  dellemc.powerflex:
    version: 2.6.1
  dellemc.unity:
    version: 2.1.0
  f5networks.f5_modules:
    version: 1.39.0
  fortinet.fortimanager:
    version: 2.11.0
  fortinet.fortios:
    version: 2.4.1
  google.cloud:
    version: 1.9.0
  grafana.grafana:
    version: 6.0.4
  hetzner.hcloud:
    version: 5.4.0
  hitachivantara.vspone_block:
    version: 4.2.2
  hitachivantara.vspone_object:
    version: 1.0.0
  ibm.qradar:
    version: 4.0.0
  ibm.storage_virtualize:
    version: 2.7.4
  ieisystem.inmanage:
    version: 3.0.0
  infinidat.infinibox:
    version: 1.6.3
  infoblox.nios_modules:
    version: 1.8.0
  inspur.ispim:
    version: 2.2.3
  junipernetworks.junos:
    version: 11.0.0
  kaytus.ksmanage:
    version: 2.0.0
  kubernetes.core:
    version: 6.1.0
  kubevirt.core:
    version: 2.2.3
  lowlydba.sqlserver:
    version: 2.7.0
  microsoft.ad:
    version: 1.9.2
  microsoft.iis:
    version: 1.0.3
  netapp.cloudmanager:
    version: 21.24.0
  netapp.ontap:
    version: 23.1.0
  netapp.storagegrid:
    version: 21.15.0
  netapp_eseries.santricity:
    version: 1.4.1
  netbox.netbox:
    version: 3.21.0
  ngine_io.cloudstack:
    version: 2.5.0
  openstack.cloud:
    version: 2.4.1
  ovirt.ovirt:
    version: 3.2.1
  purestorage.flasharray:
    version: 1.39.0
  purestorage.flashblade:
    version: 1.21.2
  ravendb.ravendb:
    version: 1.0.3
  splunk.es:
    version: 4.0.0
  telekom_mms.icinga_director:
    version: 2.4.0
  theforeman.foreman:
    version: 5.6.0
  vmware.vmware:
    version: 2.4.0
  vmware.vmware_rest:
    version: 4.9.0
  vultr.cloud:
    version: 1.13.0
  vyos.vyos:
    version: 6.0.0
  wti.remote:
    version: 1.0.10
