collections:
  - name: ansible._protomatter
    version: 2.19.3
  - name: amazon.aws
    version: 10.1.2
  - name: ansible.netcommon
    version: 8.1.0
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.0
  - name: ansible.windows
    version: 3.2.0
  - name: arista.eos
    version: 12.0.0
  - name: awx.awx
    version: 24.6.1
  - name: azure.azcollection
    version: 3.9.0
  - name: check_point.mgmt
    version: 6.5.0
  - name: chocolatey.chocolatey
    version: 1.5.3
  - name: cisco.aci
    version: 2.12.0
  - name: cisco.dnac
    version: 6.40.0
  - name: cisco.intersight
    version: 2.6.0
  - name: cisco.ios
    version: 11.1.0
  - name: cisco.iosxr
    version: 12.0.0
  - name: cisco.meraki
    version: 2.21.8
  - name: cisco.mso
    version: 2.11.0
  - name: cisco.nxos
    version: 11.0.0
  - name: cisco.ucs
    version: 1.16.0
  - name: cloudscale_ch.cloud
    version: 2.5.2
  - name: community.aws
    version: 10.0.0
  - name: community.ciscosmb
    version: 1.0.11
  - name: community.crypto
    version: 3.0.4
  - name: community.digitalocean
    version: 1.27.0
  - name: community.dns
    version: 3.3.4
  - name: community.docker
    version: 4.8.1
  - name: community.general
    version: 11.4.0
  - name: community.grafana
    version: 2.3.0
  - name: community.hashi_vault
    version: 7.0.0
  - name: community.hrobot
    version: 2.5.2
  - name: community.library_inventory_filtering_v1
    version: 1.1.4
  - name: community.libvirt
    version: 2.0.0
  - name: community.mongodb
    version: 1.7.10
  - name: community.mysql
    version: 3.16.0
  - name: community.okd
    version: 5.0.0
  - name: community.postgresql
    version: 4.1.0
  - name: community.proxmox
    version: 1.3.0
  - name: community.proxysql
    version: 1.6.0
  - name: community.rabbitmq
    version: 1.6.0
  - name: community.routeros
    version: 3.12.1
  - name: community.sap_libs
    version: 1.5.0
  - name: community.sops
    version: 2.2.4
  - name: community.vmware
    version: 5.9.0
  - name: community.windows
    version: 3.0.1
  - name: community.zabbix
    version: 4.1.1
  - name: containers.podman
    version: 1.18.0
  - name: cyberark.conjur
    version: 1.3.7
  - name: cyberark.pas
    version: 1.0.35
  - name: dellemc.enterprise_sonic
    version: 3.0.0
  - name: dellemc.openmanage
    version: 9.12.3
  - name: dellemc.powerflex
    version: 2.6.1
  - name: dellemc.unity
    version: 2.1.0
  - name: f5networks.f5_modules
    version: 1.39.0
  - name: fortinet.fortimanager
    version: 2.11.0
  - name: fortinet.fortios
    version: 2.4.1
  - name: google.cloud
    version: 1.9.0
  - name: grafana.grafana
    version: 6.0.4
  - name: hetzner.hcloud
    version: 5.4.0
  - name: hitachivantara.vspone_block
    version: 4.2.2
  - name: hitachivantara.vspone_object
    version: 1.0.0
  - name: ibm.qradar
    version: 4.0.0
  - name: ibm.storage_virtualize
    version: 2.7.4
  - name: ieisystem.inmanage
    version: 3.0.0
  - name: infinidat.infinibox
    version: 1.6.3
  - name: infoblox.nios_modules
    version: 1.8.0
  - name: inspur.ispim
    version: 2.2.3
  - name: junipernetworks.junos
    version: 11.0.0
  - name: kaytus.ksmanage
    version: 2.0.0
  - name: kubernetes.core
    version: 6.1.0
  - name: kubevirt.core
    version: 2.2.3
  - name: lowlydba.sqlserver
    version: 2.7.0
  - name: microsoft.ad
    version: 1.9.2
  - name: microsoft.iis
    version: 1.0.3
  - name: netapp.cloudmanager
    version: 21.24.0
  - name: netapp.ontap:
    version: 23.1.0
  - name: netapp.storagegrid
    version: 21.15.0
  - name: netapp_eseries.santricity
    version: 1.4.1
  - name: netbox.netbox
    version: 3.21.0
  - name: ngine_io.cloudstack
    version: 2.5.0
  - name: openstack.cloud
    version: 2.4.1
  - name: ovirt.ovirt
    version: 3.2.1
  - name: purestorage.flasharray
    version: 1.39.0
  - name: purestorage.flashblade
    version: 1.21.2
  - name: ravendb.ravendb
    version: 1.0.3
  - name: splunk.es
    version: 4.0.0
  - name: telekom_mms.icinga_director
    version: 2.4.0
  - name: theforeman.foreman
    version: 5.6.0
  - name: vmware.vmware
    version: 2.4.0
  - name: vmware.vmware_rest
    version: 4.9.0
  - name: vultr.cloud
    version: 1.13.0
  - name: vyos.vyos
    version: 6.0.0
  - name: wti.remote
    version: 1.0.10
