---
- name: jacks web stack
  hosts: aws_ec2
  become: yes

  vars:
    web_package: apache2
    web_service: apache2
    site_title: "hello from Jack's webpage!"
    doc_root: /var/www/html

  tasks:
    - name: ensure apache is installed
      apt:      
        name: "{{ web_package }}"
        state: present
        update_cache: yes
    
    - name: ensure apache is started and enabled
      service: 
        name: "{{ web_service }}"
        state: started
        enabled: yes

    - name: Ensure an images file on the target node exists
      ansible.builtin.file:
        path: /var/www/html/images
        state: directory
        mode: "0755"

    - name: Upload JPEG from control node and send it to the target node
      ansible.builtin.copy:
        src: ../photos/palm_tree.jpg          # path relative to playbook
        dest: "{{ doc_root }}/images/picture.jpg"
        owner: www-data
        group: www-data
        mode: "0644"

    - name: deploy index.html
      template:
        src: ../templates/index.html.j2
        dest: "{{ doc_root }}/index.html"
        owner: www-data
        group: www-data
        mode: '0644'
      notify: reload apache

  handlers:
    - name: reload apache
      service:
        name: "{{ web_service }}"
        state: reloaded
